name: flutter_video_cast
description: flutter_video_cast let you discover cast devices like Chrome Cast and Apple TV and connect to them.
version: 1.0.3
homepage: https://github.com/PalaTeam/flutter_video_cast

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.aesys.flutter_video_cast
        pluginClass: FlutterVideoCastPlugin
      ios:
        pluginClass: FlutterVideoCastPlugin
